#!/usr/bin/env bash
# Bring the Twenty stack to match what's currently in /opt/twenty/infra/.
# Called by:
#   - vm-startup.sh on every VM boot
#   - .github/workflows/deploy.yml on every push to main
#
# Idempotent. Safe to re-run.

set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$INFRA_DIR"

# ---------- 1. Render .env from Secret Manager + metadata ----------
IP=$(curl -fsSH 'Metadata-Flavor: Google' \
  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip)
CRM_DOMAIN="crm.${IP//./-}.nip.io"

APP_SECRET=$(gcloud secrets versions access latest --secret=twenty-app-secret)
PG_PASSWORD=$(gcloud secrets versions access latest --secret=twenty-pg-password)

umask 077
cat > .env <<EOF
# Generated by deploy.sh — DO NOT EDIT MANUALLY.
CRM_DOMAIN=${CRM_DOMAIN}
SERVER_URL=https://${CRM_DOMAIN}
APP_SECRET=${APP_SECRET}
PG_PASSWORD=${PG_PASSWORD}
EOF
umask 022

# ---------- 2. Pull + up ----------
docker compose pull
docker compose up -d --remove-orphans
docker image prune -f >/dev/null 2>&1 || true

echo "✓ deploy complete: https://${CRM_DOMAIN}"
